languages_codeforces = {
    ".NET Core C#": ".cs",
    "Clang++17 Diagnostics": ".cpp",
    "D": ".d",
    "FPC": ".pas",
    "GNU C++14": ".cpp",
    "GNU C++17": ".cpp",
    "GNU C++17 (64)": ".cpp",
    "GNU C++20 (64)": ".cpp",
    "GNU C11": ".c",
    "Go": ".go",
    "Haskell": ".hs",
    "Java 11": ".java",
    "Java 8": ".java",
    "JavaScript": ".js",
    "Kotlin 1.4": ".kt",
    "Kotlin 1.5": ".kt",
    "MS C++ 2017": ".cpp",
    "Mono C#": ".cs",
    "Node.js": ".js",
    "PHP": ".php",
    "PascalABC.NET": ".pas",
    "Perl": ".pl",
    "PyPy 2": ".py",
    "PyPy 3": ".py",
    "PyPy 3-64": ".py",
    "Python 2": ".py",
    "Python 3": ".py",
    "Ruby 3": ".rb",
    "Rust 2021": ".rs",
    "Scala": ".scala",
}
